### ISSUE TITLE
[Update] compatibility with future Typo3 versions (8 LTS, 9 LTS, ..)

### ISSUE THREAD

**Issue by medarob** [portrino/px_shopware#4]
Hi,

I just found this extensions and right now it's only available for Typo3 7 LTS.
I wanted to know if there will be support for newer Typo3 versions, like 8 LTS and later this year 9 LTS ?

Thank you very much.

**Comment by EvilBMP** [comment]
There is already a typo3-8-7 branch, which hasn't been migrated to the master yet. Please have a look and give it a try.

**Comment by tgriessbach** [comment]
Hi @medarob ,
the current master is updated for TYPO3 9.5 LTS
We are still testing it but maybe you want to take a look?
