### ISSUE TITLE
PHP 7: Incompatible declaration

### ISSUE THREAD

**Issue by cirk2** [portrino/px_shopware#6]
The method parameter type declaration in 
https://github.com/portrino/px_shopware/blob/30a497c657f22a35a96490895a78b0d032987a4b/Classes/Service/Solr/Indexer/ArticleIndexer.php#L54
is incompatible to it's parent class and therefore triggering an warning in php 7.0+:
``
TYPO3\CMS\Core\Error\Exception: PHP Warning: Declaration of Portrino\PxShopware\Service\Solr\Indexer\ArticleIndexer::itemIsValid(Portrino\PxShopware\Domain\Model\Article $article) should be compatible with Portrino\PxShopware\Service\Solr\Indexer\AbstractShopwareIndexer::itemIsValid(Portrino\PxShopware\Domain\Model\AbstractShopwareModel $itemRecord) in /var/www/vhosts/lehrer-online.de/htdocs/typo3conf/ext/px_shopware/Classes/Service/Solr/Indexer/ArticleIndexer.php line 161 in /var/www/vhosts/lehrer-online.de/vendor/typo3/cms/typo3/sysext/core/Classes/Error/ErrorHandler.php:111
``

**Comment by cirk2** [comment]
This also affects
https://github.com/portrino/px_shopware/blob/30a497c657f22a35a96490895a78b0d032987a4b/Classes/Service/Solr/Indexer/AbstractShopwareIndexer.php#L208
This also depends on the second parameter being a object while the base class defines it as array.

**Comment by EvilBMP** [comment]
Please take a look at 240a16f or/ and test with the latest revision of the "feature-lo" branch.

**Comment by cirk2** [comment]
Works. Thanks
