### ISSUE TITLE
PHP Syntax Error

### ISSUE THREAD

**Issue by benwalch** [portrino/px_shopware#9]
Extension Version: dev-master
TYPO3 Version 9.5

With having solr installed, a PHP Syntax Error occurs when saving a record in BE.
The problem is in the file Xclass/Solr/IndexQueue/Queue.php (forgot to wrap ```$queryBuiler->expr(...)``` in a ```->where()```)

The below code fixes this problem:
```
$statement = $queryBuilder
 63                     ->select('*')
 64                     ->from($table)
 65                     ->where(
 66                         $queryBuilder->expr()->in(
 67                                 'uid',
 68                                 $uidList
 69                         )
 70                     )
 71                     ->execute();
```

**Comment by aWuttig** [comment]
Thank you. Could you please make an PR?

**Comment by jonakieling** [comment]
Hi,

we stumbled upon the same error and have a PR for this here  already: https://github.com/portrino/px_shopware/pull/11

Forgot to open an issue along with it.

Kind regards
Jona

**Comment by EvilBMP** [comment]
Merged...
